services:
  valex_postgres:
    image: postgres
    container_name: valex_postgres
    restart: always
    ports:
      - 6022:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data
    
  valex_node:
    container_name: valex_node
    build: .
    ports:
      - 80:4000
    depends_on:
      - valex_postgres
    env_file:
      - .env
    
volumes:
  pg:
