services:
  valex_postgres:
    image: postgres
    container_name: valex_postgres
    restart: always
    ports:
      - 5433:5433
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data
    command: postgres -p 5433
    
  valex_node:
    container_name: valex_node
    build: .
    ports:
      - 80:4000
    depends_on:
      - valex_postgres
    env_file:
      - .env
    
volumes:
  pg:
