on:
  push:
    branches:
      - main

name: Build and Deploy
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create back-end env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_MODE: ${{ secrets.MODE }}
          envkey_POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          envkey_POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_CRYPTR_SECRET: ${{ secrets.CRYPTR_SECRET }}
          file_name: .env
          fail_on_empty: true

      - name: Build
        run: docker-compose -- build

      - name: Run
        run: docker-compose down && docker-compose up -d
